### ISSUE TITLE
Cookies?

### ISSUE THREAD

**Issue by ratalla816** [ratalla816/Forge#41]

**Comment by Derimarg** [comment]
What happen with cookies?

**Comment by ratalla816** [comment]
The requirements state, "Application includes user authentication (express-session and cookies)." 
Do we need to implement an additional feature for cookies, or are they part of our user authentication function?

**Comment by Derimarg** [comment]
I did that like last week, is in server.js

**Comment by ratalla816** [comment]
Awesome. Thank you
