### ISSUE TITLE
ensure ADA accessibility guidelines are met

### ISSUE THREAD

**Issue by ratalla816** [ratalla816/Forge#7]

**Comment by ratalla816** [comment]
npm install a11y (audits access guidelines)

**Comment by cmccray87** [comment]
Updated img files w alt attributes, pushed to branch - refactor/ada-compliance and merged with develop

**Comment by cmccray87** [comment]
initial set up of a11y npm installed and set up

**Comment by Derimarg** [comment]
great, actually we are refactoring the CSS, if you wanna help, deleting classes that we are not using.
