### ISSUE TITLE
Implement password encryption

### ISSUE THREAD

**Issue by ratalla816** [ratalla816/Forge#9]
[https://courses.bootcampspot.com/courses/715/pages/13-dot-2-3-create-a-new-feature-branch?module_item_id=228061](url)

**Comment by ratalla816** [comment]
// In this case, a login route could've used the GET method since it doesn't actually create or insert anything into the database. 
 //  But there is a reason why a POST is the standard for the login that's in process.
  router.post('/login', (req, res) => {
    // expects {email: 'rob.atalla@gmail.com', password: 'password1234'}
  User.findOne({
    where: {
      email: req.body.email
    }
  }).then(dbUserData => {
    if (!dbUserData) {
      res.status(400).json({ message: 'No user with that email address!' });
      return;
    }

    // Verify user
    const validPassword = dbUserData.checkPassword(req.body.password);

    if (!validPassword) {
        res.status(400).json({ message: 'Incorrect password!' });
        return;
      }
  
      res.json({ user: dbUserData, message: 'You are now logged in!' });
    
  });  
});

**Comment by audryf** [comment]
hash passwords using bcrypt
